### PR TITLE
Update follina.py

### PR DESCRIPTION
**Pull request by DanusMinimus**
File name fix, for some reason added extension is .tlp that would cause a "no file found" error

### CODE REVIEW

**Comment by chvancooten** [comment]
That is weird, I did test it with this extension and it works without issues. Does it return that error even if the file is present? 🤔

**Comment by chvancooten** [comment]
The template file was renamed right, so it should be here: https://github.com/chvancooten/follina.py/blob/main/src/rtf/clickme.rtf.tpl

I renamed it since this is the template for the RTF and not an actual RTF. Additionally, this allows us to add all RTF files to .gitignore so they aren't managed by git.

**Comment by DanusMinimus** [comment]
I see, Pull Request can be closed then as the problem was internal in my repo where the RTF file was not renamed with the proper name.

**Comment by chvancooten** [comment]
Cool, thanks for the confirmation!

**Pull request closed without merging**
